version: '3.5'

services:
  rabbit:
    image: rabbitmq:3-management
    ports:
    - "15672:15672"
    - "5672:5672"

  robot:
    build:
      context: .
      dockerfile: ./dockerfile.robot
      
  client:
    build:
      context: .
      dockerfile: ./dockerfile.client
      